---
apiVersion: v1
kind: Service
metadata:
  name: browser-client
  labels:
    group: browser-client
    role: browser-application
    access: external
spec:
  type: ClusterIP
  selector:
    group: browser-client
  ports:
  - name: browser-client-http
    port: 80
    targetPort: 3000
