version: "3.8"

services:
  codespace:
    init: true # possibly unneeded
    # image: ghcr.io/krainboltgreene/blank-application_devcontainer_codespace:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
    env_file: .env
    network_mode: service:postgres

  postgres:
    image: postgres:14.2
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clumsy_chinchilla_dev

volumes:
  postgres-data:
