version: "3.8"

services:
  project:
    # init: true # possibly unneeded
    # image: ghcr.io/krainboltgreene/blank-application_devcontainer_codespace:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file: .env
    network_mode: service:postgres

  postgres:
    image: postgres:14.2
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core_dev

volumes:
  postgres-data:
