use Mix.Config

Application.put_env(:find_reel_love, :domain, "localhost")
Application.put_env(:find_reel_love, :base_url, "/")

# Configure your database
config :find_reel_love, Database.Repository,
  username: "postgres",
  password: "postgres",
  database: "find_reel_love_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  prepare: :unnamed

# Configure the database for GitHub Actions
if System.get_env("GITHUB_ACTIONS") do
  config :find_reel_love, Database.Repository,
    username: "postgres",
    password: "postgres"
end

config :logger,
  backends: [:console]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :find_reel_love, Web.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/web/(live|views)/.*(ex)$",
      ~r"lib/web/templates/.*(eex)$"
    ]
  ]
config :phoenix_live_reload,
  dirs: [
    "priv/static/",
    "priv/gettext/",
    "lib/web/live/",
    "lib/web/views/",
    "lib/web/templates/"
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 10

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :find_reel_love, :graphql, uri: "/graphql"

config :find_reel_love, :flow, max_demand: 8

# Setup Bamboo mailer
config :find_reel_love, Mailer,
  adapter: Bamboo.LocalAdapter,
  open_email_in_browser_url: "/sent_emails"

if System.get_env("GITHUB_ACTIONS") do
  config :find_reel_love, Mailer,
    open_email_in_browser_url: false
end
