name: Elixir CI

on:
  push:
    branches: [ core ]
  pull_request:
    branches: [ core ]

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
  elixir-setup:
    name: Elixir Setup
    needs: cleanup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.13
        otp-version: 24
    - name: Restore mix cache
      id: mix-cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build
          priv/plts
        key: ${{ runner.os }}-24-1.13-${{ hashFiles('mix.lock') }}
    - run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
  elixir-build:
    name: Elixir Build
    needs: ["elixir-setup"]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.13
        otp-version: 24
    - name: Restore mix cache
      uses: actions/cache@v2
      id: mix-cache
      with:
        path: |
          deps
          _build
          priv/plts
        key: ${{ runner.os }}-24-1.13-${{ hashFiles('mix.lock') }}
    - run: mix compile
    - run: |
        mkdir -p priv/plts
        mix dialyzer --plt
    - run: mix ecto.setup
  elixir-check:
    name: Elixir Checks
    needs: ["elixir-build"]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.13
        otp-version: 24
    - name: Restore mix cache
      id: mix-cache
      with:
        path: |
          deps
          _build
          priv/plts
        key: ${{ runner.os }}-24-1.13-${{ hashFiles('mix.lock') }}
    - name: Restore elixir build cache
      uses: actions/cache@v2
      with:
        path: _build
        key: ${{ runner.os }}-elixir-build
    - name: Check Code Format
      run: mix format --check-formatted
    - name: Run Credo
      run: mix credo
    - name: Run Dialyzer
      run: mix dialyzer --no-check
    - run: mix test --trace --slowest 10
