name: Docker Image CI

on:
  push:
    branches: [ core ]
  pull_request:
    branches: [ core ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag clumsy_chinchilla:$(date +%s)
