name: Elixir CI
on:
  push:
    branches: [ core ]
  pull_request:
    branches: [ core ]
jobs:
  validate:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: '22.2'
        elixir-version: '1.9.4'
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
    - uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - run: mix deps.get
    - run: mix test
