name: Elixir CI

on:
  push:
    branches: [ core ]
  pull_request:
    branches: [ core ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam
      with:
        elixir-version: '1.11.4' # Define the elixir version [required]
        otp-version: '23.3' # Define the OTP version [required]
    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: _build
        key: ${{ runner.os }}-elixir-build-
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - run: bin/elixir-setup
    - run: bin/esunit-check
