name: Javascript CI

on:
  push:
    branches: [ core ]
  pull_request:
    branches: [ core ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: tmp/browser-client
        key: ${{ runner.os }}-javascript-build-
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-mix-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
    - run: bin/eslint-check
    - run: bin/typescript-check
    - run: bin/webpack-build
