name: Node.js CI
on:
  push:
    branches: [ core ]
  pull_request:
    branches: [ core ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-npm-
    - run: npm ci
    - run: bin/eslint-check
    - run: bin/typescript-check
    - run: bin/webpack-build
